name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/kollalabs

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true

    - name: Grant private modules access
      run: |
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/kollalabs".insteadOf "https://github.com/kollalabs"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Vet
      run: go vet ./...
